"""Add status column to bookings

Revision ID: a2263852f226
Revises:
Create Date: 2025-04-17 10:21:50.794251

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2263852f226"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booking", sa.Column("passenger_name", sa.String(), nullable=False))
    op.add_column("booking", sa.Column("passenger_age", sa.String(), nullable=False))
    op.add_column("booking", sa.Column("passenger_gender", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booking", "passenger_gender")
    op.drop_column("booking", "passenger_age")
    op.drop_column("booking", "passenger_name")
    # ### end Alembic commands ###
